# Extreme Reactors 2 - neoforge.mods.toml

modLoader="javafml"
loaderVersion="[4,)"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ZeroNoRyouki/ExtremeReactors2"
logoFile="logo.png"

[[mods]]
	modId="bigreactors"
    version="1.21.1-2.4.28"
    updateJSONURL="https://raw.githubusercontent.com/ZeroNoRyouki/ModUpdates/master/ExtremeReactors2.json"
	displayName="Extreme Reactors"
	authors="ZeroNoRyouki"
	description="Adds large, multiblock power generation machines to Minecraft. This is a continuation of the 1.7.10 mod Big Reactors from ErogenousBeef"

[[dependencies.bigreactors]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bigreactors]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.152,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bigreactors]]
    modId="zerocore"
    type="required"
    versionRange="[1.21.1-2.4.21,1.21.1-2.5.0)"
    ordering="AFTER"
    side="BOTH"
